#! /bin/bash

echo 'Add .gitconfig'
stow --target=$HOME git
echo 'Add tmux.conf'
stow --target=$HOME tmux

NVIM_FOLDER=~/.config/nvim
[[ ! -d "$NVIM_FOLDER" ]] && mkdir "$NVIM_FOLDER"

echo 'Add neovim'
stow -t $HOME/.config/nvim nvim

if [[ $OSTYPE == 'darwin'* ]]; then
  echo 'Add Mac .zshrc'
  stow --target=$HOME zsh-mac
elif [[ $OSTYPE == 'linux'* ]]; then
  echo 'Add Linux .zshrc'
  stow --target=$HOME zsh-linux

  echo 'Add .Xressources'
  stow --target=$HOME X

  ROFI_FOLDER=~/.config/rofi
  [[ ! -d "$ROFI_FOLDER" ]] && mkdir "$ROFI_FOLDER"

  echo 'Add rofi Configuration'
  stow -t ~/.config/rofi rofi

  AWESOME_FOLDER=~/.config/awesome
  [[ ! -d "$AWESOME_FOLDER" ]] && mkdir "$AWESOME_FOLDER"

  echo 'Add AwesomeWM Configuration'
  stow -t ~/.config/awesome awesome

  [[ -d "$AWESOME_FOLDER/lain" ]] && rm -r "$AWESOME_FOLDER/lain"
  git clone https://github.com/lcpz/lain.git ~/.config/awesome/lain
fi

npm i -g typescript-language-server

echo ''
echo "Good Job ! So now you've got fucking dotfiles !"
